language: csharp
solution: Eventure.Read.Mongo.sln
mono: none
dotnet: 2.0.3
dist: trusty
services:
   - mongodb
script:
   - dotnet restore
   - dotnet build
   - dotnet test ./Eventure.Read.Mongo.Test/Eventure.Read.Mongo.Test.csproj
